### ISSUE TITLE
Why not use Apache Echarts

### ISSUE THREAD

**Issue by simonaubertbd** [RootDBApp/rootdb#3]
Hello,

From what I understand, this is probably the best choice for dataviz
https://echarts.apache.org/en/index.html

Best regards,

Simon

**Comment by spo-ijaz** [comment]
Hi @simonaubertbd ,

I had a quick look at this library and yes, it seems a cool one.
We can probably integrate it since RootDB is designed from the ground to have the choice of the library for the charts.
Should not take too much time.
I'll test that.

**Comment by spo-ijaz** [comment]
Released in 1.1.3

**Comment by simonaubertbd** [comment]
@spo-ijaz  Thanks, great work !
